package policy

// SOC2Excerpts contains policy text for SOC2 controls
var SOC2Excerpts = map[string]string{
	"SOC2-CC1.1": "The organization demonstrates a commitment to integrity and ethical values through policies and procedures that are communicated throughout the entity.",
	"SOC2-CC1.2": "The board of directors demonstrates independence from management and exercises oversight of the development and performance of internal control.",
	"SOC2-CC1.3": "Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in the pursuit of objectives.",
	"SOC2-CC1.4": "The organization demonstrates a commitment to attract, develop, and retain competent individuals in alignment with objectives.",
	"SOC2-CC1.5": "The organization holds individuals accountable for their internal control responsibilities in the pursuit of objectives.",
	"SOC2-CC2.1": "The organization obtains or generates and uses relevant, quality information to support the functioning of internal control.",
	"SOC2-CC2.2": "The organization internally communicates information, including objectives and responsibilities for internal control, necessary to support the functioning of internal control.",
	"SOC2-CC2.3": "The organization communicates with external parties regarding matters affecting the functioning of internal control.",
	"SOC2-CC3.1": "The organization specifies objectives with sufficient clarity to enable the identification and assessment of risks relating to objectives.",
	"SOC2-CC3.2": "The organization identifies risks to the achievement of its objectives across the entity and analyzes risks as a basis for determining how the risks should be managed.",
	"SOC2-CC3.3": "The organization considers the potential for fraud in assessing risks to the achievement of objectives.",
	"SOC2-CC3.4": "The organization identifies and assesses changes that could significantly impact the system of internal control.",
	"SOC2-CC4.1": "The organization selects and develops control activities that contribute to the mitigation of risks to the achievement of objectives to acceptable levels.",
	"SOC2-CC4.2": "The organization selects and develops general control activities over technology to support the achievement of objectives.",
	"SOC2-CC5.1": "The organization selects, develops, and performs ongoing and/or separate evaluations to ascertain whether the components of internal control are present and functioning.",
	"SOC2-CC5.2": "The organization evaluates and communicates internal control deficiencies in a timely manner to those parties responsible for taking corrective action.",
	"SOC2-CC6.1": "The organization implements logical access security software, infrastructure, and architectures over protected information assets to protect them from security events to meet the entity's objectives.",
	"SOC2-CC6.2": "Prior to issuing system credentials and granting system access, the entity registers and authorizes new internal and external users whose access is administered by the entity.",
	"SOC2-CC6.3": "The organization manages the identification, authentication, and authorization of users to protected information assets.",
	"SOC2-CC6.4": "The organization restricts physical access to facilities and protected information assets to authorized personnel.",
	"SOC2-CC6.5": "The organization terminates or adjusts access to protected information assets in a timely manner for individuals whose access is no longer authorized.",
	"SOC2-CC6.6": "The organization implements logical access security measures to protect against threats from sources outside its system boundaries.",
	"SOC2-CC6.7": "The organization restricts the transmission, movement, and removal of information to authorized internal and external users and processes.",
	"SOC2-CC6.8": "The organization implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software.",
	"SOC2-CC7.1": "To meet its objectives, the organization uses detection and monitoring procedures to identify anomalies.",
	"SOC2-CC7.2": "The organization monitors system components and the operation of those components for anomalies that are indicative of malicious acts, natural disasters, and errors.",
	"SOC2-CC7.3": "The organization evaluates security events to determine whether they could or have resulted in a failure of controls.",
	"SOC2-CC7.4": "The organization responds to identified security incidents by executing a defined incident response program.",
	"SOC2-CC7.5": "The organization identifies, develops, and implements activities to recover from identified security incidents.",
	"SOC2-CC8.1": "The organization authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures to meet its objectives.",
	"SOC2-CC9.1": "The organization identifies, selects, and develops risk mitigation activities for risks arising from potential business disruptions.",
	"SOC2-CC9.2": "The organization assesses and manages risks associated with vendors and business partners.",
}

// ISO27001Excerpts contains policy text for ISO 27001 controls
var ISO27001Excerpts = map[string]string{
	"ISO27001-A.5.1":  "Management direction for information security: Policies for information security and their review.",
	"ISO27001-A.6.1":  "Internal organization: Information security roles and responsibilities.",
	"ISO27001-A.6.2":  "Mobile devices and teleworking: Policy and supporting security measures.",
	"ISO27001-A.7.1":  "Prior to employment: Screening and background verification.",
	"ISO27001-A.7.2":  "During employment: Management responsibilities and awareness.",
	"ISO27001-A.7.3":  "Termination and change of employment: Protection of organization's interests.",
	"ISO27001-A.8.1":  "Responsibility for assets: Inventory and ownership.",
	"ISO27001-A.8.2":  "Information classification: Classification guidelines and labeling.",
	"ISO27001-A.8.3":  "Media handling: Procedures for managing removable media.",
	"ISO27001-A.9.1":  "Business requirements of access control: Access control policy.",
	"ISO27001-A.9.2":  "User access management: User registration and de-registration.",
	"ISO27001-A.9.3":  "User responsibilities: Secret authentication information usage.",
	"ISO27001-A.9.4":  "System and application access control: Information access restriction.",
	"ISO27001-A.10.1": "Cryptographic controls: Policy on the use of cryptographic controls.",
	"ISO27001-A.11.1": "Secure areas: Physical security perimeter and entry controls.",
	"ISO27001-A.11.2": "Equipment: Equipment siting and protection, supporting utilities.",
	"ISO27001-A.12.1": "Operational procedures and responsibilities: Documented procedures.",
	"ISO27001-A.12.2": "Protection from malware: Controls and user awareness.",
	"ISO27001-A.12.3": "Backup: Information backup procedures.",
	"ISO27001-A.12.4": "Logging and monitoring: Event logging and clock synchronization.",
	"ISO27001-A.12.5": "Control of operational software: Installation procedures.",
	"ISO27001-A.12.6": "Technical vulnerability management: Management of technical vulnerabilities.",
	"ISO27001-A.12.7": "Information systems audit considerations: Audit activities planning.",
	"ISO27001-A.13.1": "Network security management: Network controls and services.",
	"ISO27001-A.13.2": "Information transfer: Policies, procedures and controls.",
	"ISO27001-A.14.1": "Security requirements of information systems: Analysis and specification.",
	"ISO27001-A.14.2": "Security in development and support processes: Secure development policy.",
	"ISO27001-A.14.3": "Test data: Protection of test data.",
	"ISO27001-A.15.1": "Information security in supplier relationships: Policy and agreements.",
	"ISO27001-A.15.2": "Supplier service delivery management: Monitoring and review.",
	"ISO27001-A.16.1": "Management of information security incidents: Responsibilities and procedures.",
	"ISO27001-A.17.1": "Information security continuity: Planning and implementation.",
	"ISO27001-A.17.2": "Redundancies: Availability of information processing facilities.",
	"ISO27001-A.18.1": "Compliance with legal and contractual requirements: Identification of applicable legislation.",
	"ISO27001-A.18.2": "Information security reviews: Independent review and compliance.",
}

// PCIDSSExcerpts contains policy text for PCI DSS controls
var PCIDSSExcerpts = map[string]string{
	"PCI-DSS-1":  "Install and maintain a firewall configuration to protect cardholder data.",
	"PCI-DSS-2":  "Do not use vendor-supplied defaults for system passwords and other security parameters.",
	"PCI-DSS-3":  "Protect stored cardholder data through encryption and data retention policies.",
	"PCI-DSS-4":  "Encrypt transmission of cardholder data across open, public networks.",
	"PCI-DSS-5":  "Protect all systems against malware and regularly update anti-virus software or programs.",
	"PCI-DSS-6":  "Develop and maintain secure systems and applications through security patches and secure coding practices.",
	"PCI-DSS-7":  "Restrict access to cardholder data by business need to know through role-based access controls.",
	"PCI-DSS-8":  "Identify and authenticate access to system components through unique IDs and strong authentication.",
	"PCI-DSS-9":  "Restrict physical access to cardholder data through facility entry controls and monitoring.",
	"PCI-DSS-10": "Track and monitor all access to network resources and cardholder data through logging and monitoring.",
	"PCI-DSS-11": "Regularly test security systems and processes through vulnerability scans and penetration testing.",
	"PCI-DSS-12": "Maintain a policy that addresses information security for all personnel through documentation and training.",
}
