package analyze

import "github.com/pickjonathan/sdek-cli/pkg/types"

// FrameworkDefinition contains the metadata and controls for a compliance framework
type FrameworkDefinition struct {
	ID          string
	Name        string
	Description string
	Controls    []ControlDefinition
}

// ControlDefinition contains the metadata and keywords for a control
type ControlDefinition struct {
	ID          string
	Title       string
	Description string
	Category    string
	Keywords    []string
}

// GetFrameworkDefinitions returns all available framework definitions
func GetFrameworkDefinitions() map[string]FrameworkDefinition {
	return map[string]FrameworkDefinition{
		string(types.FrameworkSOC2):     GetSOC2Framework(),
		string(types.FrameworkISO27001): GetISO27001Framework(),
		string(types.FrameworkPCIDSS):   GetPCIDSSFramework(),
	}
}

// GetSOC2Framework returns the SOC2 framework definition with 45 controls
func GetSOC2Framework() FrameworkDefinition {
	return FrameworkDefinition{
		ID:          string(types.FrameworkSOC2),
		Name:        "SOC 2",
		Description: "Service Organization Control 2 - Trust Services Criteria",
		Controls: []ControlDefinition{
			// Security (15 controls)
			{
				ID:          "CC6.1",
				Title:       "Logical and Physical Access Controls",
				Description: "The entity implements logical access security software, infrastructure, and architectures over protected information assets",
				Category:    "Security",
				Keywords:    []string{"access control", "authentication", "authorization", "login", "rbac", "permission", "credential"},
			},
			{
				ID:          "CC6.2",
				Title:       "Access Authorization",
				Description: "Prior to issuing system credentials and granting system access, authorized users are identified and authenticated",
				Category:    "Security",
				Keywords:    []string{"authentication", "user management", "identity", "verification", "mfa", "multi-factor", "sso"},
			},
			{
				ID:          "CC6.3",
				Title:       "Access Removal",
				Description: "The entity authorizes, modifies, or removes access to data, software, functions, and other protected information assets",
				Category:    "Security",
				Keywords:    []string{"deprovisioning", "access removal", "offboarding", "revoke", "disable account"},
			},
			{
				ID:          "CC6.6",
				Title:       "Encryption",
				Description: "The entity implements encryption to protect data at rest and in transit",
				Category:    "Security",
				Keywords:    []string{"encryption", "crypto", "tls", "ssl", "https", "cipher", "decrypt"},
			},
			{
				ID:          "CC6.7",
				Title:       "Transmission Security",
				Description: "The entity restricts the transmission, movement, and removal of information",
				Category:    "Security",
				Keywords:    []string{"transmission", "data transfer", "network security", "firewall", "vpn"},
			},
			{
				ID:          "CC7.1",
				Title:       "System Operations",
				Description: "Procedures exist to monitor system components and protect against unauthorized access",
				Category:    "Security",
				Keywords:    []string{"monitoring", "alerting", "security scan", "vulnerability", "intrusion detection"},
			},
			{
				ID:          "CC7.2",
				Title:       "Change Management",
				Description: "The entity implements policies for changes to existing systems",
				Category:    "Security",
				Keywords:    []string{"change management", "deployment", "release", "patch", "update"},
			},
			{
				ID:          "CC7.3",
				Title:       "Incident Response",
				Description: "The entity identifies, responds to, and communicates security incidents",
				Category:    "Security",
				Keywords:    []string{"incident", "security event", "breach", "incident response", "alert"},
			},
			{
				ID:          "CC7.4",
				Title:       "Vulnerability Management",
				Description: "The entity identifies, reports, and addresses vulnerabilities",
				Category:    "Security",
				Keywords:    []string{"vulnerability", "cve", "security patch", "remediation", "vulnerability scan"},
			},
			{
				ID:          "CC7.5",
				Title:       "Data Protection",
				Description: "The entity protects confidential information during storage, use, and transmission",
				Category:    "Security",
				Keywords:    []string{"data protection", "confidential", "pii", "sensitive data", "data security"},
			},
			{
				ID:          "CC8.1",
				Title:       "Change Controls",
				Description: "The entity authorizes, designs, develops, and tests changes to systems",
				Category:    "Security",
				Keywords:    []string{"code review", "testing", "qa", "pull request", "merge"},
			},
			{
				ID:          "CC9.1",
				Title:       "Risk Assessment",
				Description: "The entity identifies and assesses risks that could affect objectives",
				Category:    "Security",
				Keywords:    []string{"risk assessment", "threat model", "security review", "risk analysis"},
			},
			{
				ID:          "CC9.2",
				Title:       "Risk Mitigation",
				Description: "The entity designs and implements mitigation activities for identified risks",
				Category:    "Security",
				Keywords:    []string{"mitigation", "remediation", "security fix", "risk treatment"},
			},
			{
				ID:          "A1.1",
				Title:       "Availability Monitoring",
				Description: "The entity monitors system availability and capacity",
				Category:    "Availability",
				Keywords:    []string{"uptime", "availability", "monitoring", "health check", "service status"},
			},
			{
				ID:          "A1.2",
				Title:       "Backup and Recovery",
				Description: "The entity maintains backup and disaster recovery procedures",
				Category:    "Availability",
				Keywords:    []string{"backup", "restore", "disaster recovery", "failover", "redundancy"},
			},
			// Confidentiality (10 controls)
			{
				ID:          "C1.1",
				Title:       "Confidential Information",
				Description: "The entity identifies and maintains confidential information",
				Category:    "Confidentiality",
				Keywords:    []string{"confidential", "secret", "private", "classified", "sensitive"},
			},
			{
				ID:          "C1.2",
				Title:       "Disposal of Confidential Information",
				Description: "The entity disposes of confidential information securely",
				Category:    "Confidentiality",
				Keywords:    []string{"disposal", "deletion", "purge", "sanitization", "data destruction"},
			},
			{
				ID:          "P1.1",
				Title:       "Privacy Notice",
				Description: "The entity provides notice about privacy practices",
				Category:    "Privacy",
				Keywords:    []string{"privacy policy", "privacy notice", "data collection", "consent"},
			},
			{
				ID:          "P2.1",
				Title:       "Data Subject Rights",
				Description: "The entity provides data subjects with access to their personal information",
				Category:    "Privacy",
				Keywords:    []string{"data subject", "gdpr", "privacy rights", "data access", "data portability"},
			},
			{
				ID:          "P3.1",
				Title:       "Data Retention",
				Description: "The entity retains personal information consistent with objectives",
				Category:    "Privacy",
				Keywords:    []string{"retention", "data retention", "archive", "data lifecycle"},
			},
			{
				ID:          "P3.2",
				Title:       "Data Disposal",
				Description: "The entity disposes of personal information securely",
				Category:    "Privacy",
				Keywords:    []string{"data deletion", "right to erasure", "data disposal"},
			},
			{
				ID:          "P4.1",
				Title:       "Privacy Complaints",
				Description: "The entity addresses privacy complaints and disputes",
				Category:    "Privacy",
				Keywords:    []string{"privacy complaint", "data breach notification", "privacy incident"},
			},
			{
				ID:          "P4.2",
				Title:       "Privacy Monitoring",
				Description: "The entity monitors compliance with privacy commitments",
				Category:    "Privacy",
				Keywords:    []string{"privacy monitoring", "compliance check", "privacy audit"},
			},
			{
				ID:          "P5.1",
				Title:       "Third-Party Privacy",
				Description: "The entity obtains commitments from third parties regarding privacy",
				Category:    "Privacy",
				Keywords:    []string{"third party", "vendor", "subprocessor", "data sharing"},
			},
			{
				ID:          "P6.1",
				Title:       "Privacy Training",
				Description: "The entity provides privacy training to personnel",
				Category:    "Privacy",
				Keywords:    []string{"privacy training", "awareness", "education"},
			},
			// Processing Integrity (10 controls)
			{
				ID:          "PI1.1",
				Title:       "Data Quality",
				Description: "The entity maintains complete, accurate, and valid data",
				Category:    "Processing Integrity",
				Keywords:    []string{"data quality", "validation", "data integrity", "accuracy"},
			},
			{
				ID:          "PI1.2",
				Title:       "Processing Accuracy",
				Description: "The entity processes data completely, accurately, and timely",
				Category:    "Processing Integrity",
				Keywords:    []string{"processing", "transaction", "computation", "calculation"},
			},
			{
				ID:          "PI1.3",
				Title:       "Error Detection",
				Description: "The entity detects and corrects processing errors",
				Category:    "Processing Integrity",
				Keywords:    []string{"error handling", "exception", "error detection", "validation"},
			},
			{
				ID:          "PI1.4",
				Title:       "Processing Authorization",
				Description: "The entity authorizes processing activities",
				Category:    "Processing Integrity",
				Keywords:    []string{"authorization", "approval", "workflow"},
			},
			{
				ID:          "PI1.5",
				Title:       "Processing Monitoring",
				Description: "The entity monitors processing activities",
				Category:    "Processing Integrity",
				Keywords:    []string{"monitoring", "observability", "metrics", "logging"},
			},
			// Common Criteria (10 controls)
			{
				ID:          "CC1.1",
				Title:       "Control Environment",
				Description: "The entity demonstrates commitment to integrity and ethical values",
				Category:    "Common Criteria",
				Keywords:    []string{"governance", "policy", "code of conduct", "ethics"},
			},
			{
				ID:          "CC1.2",
				Title:       "Board Independence",
				Description: "The board demonstrates independence from management",
				Category:    "Common Criteria",
				Keywords:    []string{"board", "oversight", "governance", "independence"},
			},
			{
				ID:          "CC1.3",
				Title:       "Organizational Structure",
				Description: "Management establishes structures, reporting lines, and authorities",
				Category:    "Common Criteria",
				Keywords:    []string{"organization", "reporting", "structure", "hierarchy"},
			},
			{
				ID:          "CC1.4",
				Title:       "Competence",
				Description: "The entity demonstrates commitment to competence",
				Category:    "Common Criteria",
				Keywords:    []string{"training", "competence", "skills", "development"},
			},
			{
				ID:          "CC1.5",
				Title:       "Accountability",
				Description: "The entity holds individuals accountable",
				Category:    "Common Criteria",
				Keywords:    []string{"accountability", "responsibility", "ownership"},
			},
			{
				ID:          "CC2.1",
				Title:       "Communication of Objectives",
				Description: "The entity communicates objectives to enable identification of risks",
				Category:    "Common Criteria",
				Keywords:    []string{"objectives", "goals", "communication"},
			},
			{
				ID:          "CC2.2",
				Title:       "Internal Communication",
				Description: "Internal communication enables the internal control system to function",
				Category:    "Common Criteria",
				Keywords:    []string{"communication", "information sharing", "collaboration"},
			},
			{
				ID:          "CC2.3",
				Title:       "External Communication",
				Description: "The entity communicates with external parties",
				Category:    "Common Criteria",
				Keywords:    []string{"external communication", "reporting", "disclosure"},
			},
			{
				ID:          "CC3.1",
				Title:       "Risk Identification",
				Description: "The entity identifies risks to objectives",
				Category:    "Common Criteria",
				Keywords:    []string{"risk identification", "threat", "risk assessment"},
			},
			{
				ID:          "CC3.2",
				Title:       "Risk Analysis",
				Description: "The entity analyzes identified risks",
				Category:    "Common Criteria",
				Keywords:    []string{"risk analysis", "impact", "likelihood", "severity"},
			},
			{
				ID:          "CC4.1",
				Title:       "Control Activities",
				Description: "The entity implements control activities",
				Category:    "Common Criteria",
				Keywords:    []string{"control", "policy enforcement", "procedure"},
			},
			{
				ID:          "CC4.2",
				Title:       "Technology Controls",
				Description: "The entity implements controls over technology",
				Category:    "Common Criteria",
				Keywords:    []string{"technology", "system", "infrastructure", "platform"},
			},
			{
				ID:          "CC5.1",
				Title:       "Control Monitoring",
				Description: "The entity monitors the internal control system",
				Category:    "Common Criteria",
				Keywords:    []string{"monitoring", "oversight", "review", "assessment"},
			},
			{
				ID:          "CC5.2",
				Title:       "Control Deficiencies",
				Description: "The entity evaluates and communicates control deficiencies",
				Category:    "Common Criteria",
				Keywords:    []string{"deficiency", "weakness", "gap", "finding"},
			},
			{
				ID:          "CC5.3",
				Title:       "Remediation",
				Description: "The entity remediates identified control deficiencies",
				Category:    "Common Criteria",
				Keywords:    []string{"remediation", "correction", "fix", "improvement"},
			},
		},
	}
}

// GetISO27001Framework returns the ISO 27001 framework definition with 64 controls
func GetISO27001Framework() FrameworkDefinition {
	return FrameworkDefinition{
		ID:          string(types.FrameworkISO27001),
		Name:        "ISO 27001",
		Description: "International standard for information security management systems",
		Controls: []ControlDefinition{
			// A.5: Organizational controls (15 controls)
			{
				ID:          "A.5.1",
				Title:       "Information Security Policies",
				Description: "Policies for information security defined and approved by management",
				Category:    "Organizational",
				Keywords:    []string{"policy", "information security", "governance", "management approval"},
			},
			{
				ID:          "A.5.2",
				Title:       "Information Security Roles",
				Description: "Information security roles and responsibilities are defined and allocated",
				Category:    "Organizational",
				Keywords:    []string{"roles", "responsibilities", "accountability", "assignment"},
			},
			{
				ID:          "A.5.3",
				Title:       "Segregation of Duties",
				Description: "Conflicting duties and areas of responsibility are segregated",
				Category:    "Organizational",
				Keywords:    []string{"segregation", "separation of duties", "conflict of interest"},
			},
			{
				ID:          "A.5.7",
				Title:       "Threat Intelligence",
				Description: "Information about information security threats is collected and analyzed",
				Category:    "Organizational",
				Keywords:    []string{"threat intelligence", "threat", "security intelligence", "threat analysis"},
			},
			{
				ID:          "A.5.10",
				Title:       "Acceptable Use",
				Description: "Rules for acceptable use of information and assets are identified",
				Category:    "Organizational",
				Keywords:    []string{"acceptable use", "usage policy", "aup"},
			},
			{
				ID:          "A.5.14",
				Title:       "Information Transfer",
				Description: "Information transfer rules, procedures, and controls are in place",
				Category:    "Organizational",
				Keywords:    []string{"information transfer", "data transfer", "transmission"},
			},
			{
				ID:          "A.5.4",
				Title:       "Management Responsibilities",
				Description: "Management responsibilities for information security are defined",
				Category:    "Organizational",
				Keywords:    []string{"management", "leadership", "responsibility"},
			},
			{
				ID:          "A.5.5",
				Title:       "Contact with Authorities",
				Description: "Appropriate contacts with authorities are maintained",
				Category:    "Organizational",
				Keywords:    []string{"authorities", "law enforcement", "regulatory", "compliance"},
			},
			{
				ID:          "A.5.6",
				Title:       "Contact with Special Interest Groups",
				Description: "Contact with security forums and special interest groups is maintained",
				Category:    "Organizational",
				Keywords:    []string{"security forum", "industry group", "information sharing"},
			},
			{
				ID:          "A.5.8",
				Title:       "Information Security in Projects",
				Description: "Information security is integrated into project management",
				Category:    "Organizational",
				Keywords:    []string{"project management", "project security", "sdlc"},
			},
			{
				ID:          "A.5.9",
				Title:       "Inventory of Assets",
				Description: "An inventory of information and assets is maintained",
				Category:    "Organizational",
				Keywords:    []string{"asset inventory", "asset management", "cmdb"},
			},
			{
				ID:          "A.5.11",
				Title:       "Return of Assets",
				Description: "Personnel return all assets upon termination",
				Category:    "Organizational",
				Keywords:    []string{"asset return", "offboarding", "equipment return"},
			},
			{
				ID:          "A.5.12",
				Title:       "Classification of Information",
				Description: "Information is classified according to its importance",
				Category:    "Organizational",
				Keywords:    []string{"classification", "data classification", "confidentiality"},
			},
			{
				ID:          "A.5.13",
				Title:       "Labelling of Information",
				Description: "Information is labelled according to its classification",
				Category:    "Organizational",
				Keywords:    []string{"labelling", "data label", "marking"},
			},
			{
				ID:          "A.5.15",
				Title:       "Access Control",
				Description: "Rules to control physical and logical access are established",
				Category:    "Organizational",
				Keywords:    []string{"access control policy", "access rules", "authorization policy"},
			},
			// A.6: People controls (8 controls)
			{
				ID:          "A.6.1",
				Title:       "Screening",
				Description: "Background verification checks on candidates are carried out",
				Category:    "People",
				Keywords:    []string{"background check", "screening", "verification"},
			},
			{
				ID:          "A.6.2",
				Title:       "Terms of Employment",
				Description: "Employment agreements include information security responsibilities",
				Category:    "People",
				Keywords:    []string{"employment agreement", "contract", "terms"},
			},
			{
				ID:          "A.6.3",
				Title:       "Security Awareness",
				Description: "Personnel receive appropriate security awareness training",
				Category:    "People",
				Keywords:    []string{"security awareness", "training", "education"},
			},
			{
				ID:          "A.6.4",
				Title:       "Disciplinary Process",
				Description: "Disciplinary process for information security violations is in place",
				Category:    "People",
				Keywords:    []string{"disciplinary", "violation", "enforcement"},
			},
			{
				ID:          "A.6.5",
				Title:       "Termination Responsibilities",
				Description: "Information security responsibilities after employment termination are defined",
				Category:    "People",
				Keywords:    []string{"termination", "offboarding", "exit"},
			},
			{
				ID:          "A.6.8",
				Title:       "Remote Working",
				Description: "Security measures for remote working are implemented",
				Category:    "People",
				Keywords:    []string{"remote work", "work from home", "telecommuting", "vpn"},
			},
			{
				ID:          "A.6.6",
				Title:       "Confidentiality Agreements",
				Description: "Confidentiality or non-disclosure agreements are in place",
				Category:    "People",
				Keywords:    []string{"nda", "confidentiality agreement", "non-disclosure"},
			},
			{
				ID:          "A.6.7",
				Title:       "Information Security Event Reporting",
				Description: "Personnel report observed or suspected security events",
				Category:    "People",
				Keywords:    []string{"security event", "incident reporting", "security alert"},
			},
			// A.7: Physical controls (7 controls)
			{
				ID:          "A.7.1",
				Title:       "Physical Security Perimeters",
				Description: "Physical security perimeters protect areas with information assets",
				Category:    "Physical",
				Keywords:    []string{"physical security", "perimeter", "facility", "datacenter"},
			},
			{
				ID:          "A.7.2",
				Title:       "Physical Entry",
				Description: "Secure areas are protected by entry controls",
				Category:    "Physical",
				Keywords:    []string{"physical access", "entry control", "badge", "access card"},
			},
			{
				ID:          "A.7.4",
				Title:       "Physical Security Monitoring",
				Description: "Premises are continuously monitored for unauthorized physical access",
				Category:    "Physical",
				Keywords:    []string{"physical monitoring", "surveillance", "cctv", "security camera"},
			},
			{
				ID:          "A.7.3",
				Title:       "Securing Offices and Facilities",
				Description: "Security for offices and facilities is designed and implemented",
				Category:    "Physical",
				Keywords:    []string{"office security", "facility security", "building security"},
			},
			{
				ID:          "A.7.5",
				Title:       "Physical Asset Protection",
				Description: "Physical assets are protected against environmental threats",
				Category:    "Physical",
				Keywords:    []string{"asset protection", "environmental", "fire suppression", "power"},
			},
			{
				ID:          "A.7.6",
				Title:       "Working in Secure Areas",
				Description: "Security measures for working in secure areas are implemented",
				Category:    "Physical",
				Keywords:    []string{"secure area", "restricted area", "clean desk"},
			},
			{
				ID:          "A.7.7",
				Title:       "Clear Desk and Screen",
				Description: "Clear desk and clear screen policies are enforced",
				Category:    "Physical",
				Keywords:    []string{"clear desk", "clean desk", "clear screen", "visual privacy"},
			},
			// A.8: Technological controls (34 controls)
			{
				ID:          "A.8.1",
				Title:       "User Endpoint Devices",
				Description: "Information on user endpoint devices is protected",
				Category:    "Technological",
				Keywords:    []string{"endpoint", "device", "laptop", "workstation", "mobile"},
			},
			{
				ID:          "A.8.2",
				Title:       "Privileged Access Rights",
				Description: "Allocation of privileged access rights is restricted and controlled",
				Category:    "Technological",
				Keywords:    []string{"privileged access", "admin", "root", "sudo", "elevated privileges"},
			},
			{
				ID:          "A.8.3",
				Title:       "Information Access Restriction",
				Description: "Access to information and systems is restricted",
				Category:    "Technological",
				Keywords:    []string{"access restriction", "access control", "authorization"},
			},
			{
				ID:          "A.8.4",
				Title:       "Access to Source Code",
				Description: "Access to source code is appropriately controlled",
				Category:    "Technological",
				Keywords:    []string{"source code", "repository", "version control", "git"},
			},
			{
				ID:          "A.8.5",
				Title:       "Secure Authentication",
				Description: "Secure authentication technologies and procedures are implemented",
				Category:    "Technological",
				Keywords:    []string{"authentication", "login", "password", "mfa", "multi-factor"},
			},
			{
				ID:          "A.8.6",
				Title:       "Capacity Management",
				Description: "Use of resources is monitored and projections of capacity are made",
				Category:    "Technological",
				Keywords:    []string{"capacity", "performance", "resources", "scaling"},
			},
			{
				ID:          "A.8.7",
				Title:       "Protection Against Malware",
				Description: "Protection against malware is implemented",
				Category:    "Technological",
				Keywords:    []string{"malware", "antivirus", "malware protection", "virus"},
			},
			{
				ID:          "A.8.8",
				Title:       "Technical Vulnerability Management",
				Description: "Information about technical vulnerabilities is obtained and managed",
				Category:    "Technological",
				Keywords:    []string{"vulnerability management", "vulnerability", "cve", "patch management"},
			},
			{
				ID:          "A.8.9",
				Title:       "Configuration Management",
				Description: "Configurations of hardware, software, services and networks are established",
				Category:    "Technological",
				Keywords:    []string{"configuration", "configuration management", "baseline", "hardening"},
			},
			{
				ID:          "A.8.10",
				Title:       "Information Deletion",
				Description: "Information stored in systems is deleted when no longer required",
				Category:    "Technological",
				Keywords:    []string{"deletion", "data deletion", "cleanup", "purge"},
			},
			{
				ID:          "A.8.11",
				Title:       "Data Masking",
				Description: "Data masking is used in accordance with access control policy",
				Category:    "Technological",
				Keywords:    []string{"masking", "obfuscation", "anonymization", "pseudonymization"},
			},
			{
				ID:          "A.8.12",
				Title:       "Data Leakage Prevention",
				Description: "Data leakage prevention measures are applied",
				Category:    "Technological",
				Keywords:    []string{"dlp", "data leakage", "data loss prevention", "exfiltration"},
			},
			{
				ID:          "A.8.13",
				Title:       "Information Backup",
				Description: "Backup copies of information and software are maintained",
				Category:    "Technological",
				Keywords:    []string{"backup", "restore", "recovery", "snapshot"},
			},
			{
				ID:          "A.8.14",
				Title:       "Redundancy of Information Processing",
				Description: "Information processing facilities are implemented with redundancy",
				Category:    "Technological",
				Keywords:    []string{"redundancy", "high availability", "failover", "clustering"},
			},
			{
				ID:          "A.8.15",
				Title:       "Logging",
				Description: "Logs that record activities, exceptions and events are produced and retained",
				Category:    "Technological",
				Keywords:    []string{"logging", "log", "audit log", "event log"},
			},
			{
				ID:          "A.8.16",
				Title:       "Monitoring Activities",
				Description: "Networks, systems and applications are monitored for anomalies",
				Category:    "Technological",
				Keywords:    []string{"monitoring", "alerting", "anomaly detection", "siem"},
			},
			{
				ID:          "A.8.17",
				Title:       "Clock Synchronization",
				Description: "Clocks of information processing systems are synchronized",
				Category:    "Technological",
				Keywords:    []string{"time sync", "ntp", "clock synchronization"},
			},
			{
				ID:          "A.8.18",
				Title:       "Privileged Utility Programs",
				Description: "Use of utility programs that can override controls is restricted",
				Category:    "Technological",
				Keywords:    []string{"utility", "privileged program", "system tool"},
			},
			{
				ID:          "A.8.19",
				Title:       "Software Installation",
				Description: "Procedures to control installation of software are implemented",
				Category:    "Technological",
				Keywords:    []string{"software installation", "package management", "deployment"},
			},
			{
				ID:          "A.8.20",
				Title:       "Networks Security",
				Description: "Networks and network devices are secured",
				Category:    "Technological",
				Keywords:    []string{"network security", "firewall", "network segmentation"},
			},
			{
				ID:          "A.8.21",
				Title:       "Network Services Security",
				Description: "Security mechanisms, service levels and requirements of network services are identified",
				Category:    "Technological",
				Keywords:    []string{"network service", "api security", "service security"},
			},
			{
				ID:          "A.8.22",
				Title:       "Segregation of Networks",
				Description: "Groups of information services, users and information systems are segregated",
				Category:    "Technological",
				Keywords:    []string{"network segregation", "vlan", "subnet", "isolation"},
			},
			{
				ID:          "A.8.23",
				Title:       "Web Filtering",
				Description: "Access to external websites is managed",
				Category:    "Technological",
				Keywords:    []string{"web filtering", "url filtering", "content filtering"},
			},
			{
				ID:          "A.8.24",
				Title:       "Cryptographic Controls",
				Description: "Rules for effective use of cryptography are defined and implemented",
				Category:    "Technological",
				Keywords:    []string{"cryptography", "encryption", "crypto", "cipher", "tls", "ssl"},
			},
			{
				ID:          "A.8.25",
				Title:       "Secure Development Lifecycle",
				Description: "Rules for secure development of software and systems are established",
				Category:    "Technological",
				Keywords:    []string{"secure development", "sdlc", "secure coding", "development lifecycle"},
			},
			{
				ID:          "A.8.26",
				Title:       "Application Security Requirements",
				Description: "Security requirements are identified and applied to application development",
				Category:    "Technological",
				Keywords:    []string{"application security", "security requirements", "appsec"},
			},
			{
				ID:          "A.8.27",
				Title:       "Secure System Architecture",
				Description: "Principles for engineering secure systems are established",
				Category:    "Technological",
				Keywords:    []string{"system architecture", "security architecture", "design"},
			},
			{
				ID:          "A.8.28",
				Title:       "Secure Coding",
				Description: "Secure coding principles are applied to software development",
				Category:    "Technological",
				Keywords:    []string{"secure coding", "code quality", "static analysis", "code review"},
			},
			{
				ID:          "A.8.29",
				Title:       "Security Testing",
				Description: "Security testing is conducted during development",
				Category:    "Technological",
				Keywords:    []string{"security testing", "penetration test", "security scan", "vulnerability assessment"},
			},
			{
				ID:          "A.8.30",
				Title:       "Outsourced Development",
				Description: "The organization supervises and monitors outsourced development",
				Category:    "Technological",
				Keywords:    []string{"outsourced development", "third-party development", "vendor"},
			},
			{
				ID:          "A.8.31",
				Title:       "Development and Production Separation",
				Description: "Development, test and production environments are separated",
				Category:    "Technological",
				Keywords:    []string{"environment separation", "dev", "test", "production", "staging"},
			},
			{
				ID:          "A.8.32",
				Title:       "Change Management",
				Description: "Changes to information processing facilities are subject to change management",
				Category:    "Technological",
				Keywords:    []string{"change management", "change control", "deployment", "release"},
			},
			{
				ID:          "A.8.33",
				Title:       "Test Information",
				Description: "Test data is selected, protected and managed",
				Category:    "Technological",
				Keywords:    []string{"test data", "testing", "test environment"},
			},
			{
				ID:          "A.8.34",
				Title:       "Protection of Information Systems During Audit",
				Description: "Audit activities involving verification of operational systems are planned",
				Category:    "Technological",
				Keywords:    []string{"audit", "audit testing", "system audit"},
			},
		},
	}
}

// GetPCIDSSFramework returns the PCI DSS framework definition with 15 key controls
func GetPCIDSSFramework() FrameworkDefinition {
	return FrameworkDefinition{
		ID:          string(types.FrameworkPCIDSS),
		Name:        "PCI DSS",
		Description: "Payment Card Industry Data Security Standard",
		Controls: []ControlDefinition{
			{
				ID:          "1.1",
				Title:       "Firewall Configuration",
				Description: "Install and maintain firewall configuration to protect cardholder data",
				Category:    "Network Security",
				Keywords:    []string{"firewall", "network security", "network protection", "perimeter"},
			},
			{
				ID:          "2.1",
				Title:       "Vendor Defaults",
				Description: "Do not use vendor-supplied defaults for security parameters",
				Category:    "Configuration",
				Keywords:    []string{"default password", "default configuration", "hardening", "baseline"},
			},
			{
				ID:          "3.1",
				Title:       "Data Retention",
				Description: "Keep cardholder data storage to a minimum",
				Category:    "Data Protection",
				Keywords:    []string{"data retention", "cardholder data", "data storage", "data minimization"},
			},
			{
				ID:          "4.1",
				Title:       "Encryption in Transit",
				Description: "Use strong cryptography for transmission of cardholder data",
				Category:    "Cryptography",
				Keywords:    []string{"encryption", "tls", "ssl", "transmission security", "data in transit"},
			},
			{
				ID:          "5.1",
				Title:       "Anti-Malware",
				Description: "Protect all systems against malware",
				Category:    "Malware Protection",
				Keywords:    []string{"antivirus", "malware", "malware protection", "anti-malware"},
			},
			{
				ID:          "6.1",
				Title:       "Secure Systems",
				Description: "Develop and maintain secure systems and applications",
				Category:    "Application Security",
				Keywords:    []string{"secure development", "application security", "vulnerability management", "patch"},
			},
			{
				ID:          "7.1",
				Title:       "Access Control",
				Description: "Restrict access to cardholder data by business need to know",
				Category:    "Access Control",
				Keywords:    []string{"access control", "least privilege", "need to know", "authorization"},
			},
			{
				ID:          "8.1",
				Title:       "User Identification",
				Description: "Identify and authenticate access to system components",
				Category:    "Authentication",
				Keywords:    []string{"authentication", "user identification", "identity", "login"},
			},
			{
				ID:          "8.3",
				Title:       "Multi-Factor Authentication",
				Description: "Secure remote access with multi-factor authentication",
				Category:    "Authentication",
				Keywords:    []string{"mfa", "multi-factor", "two-factor", "2fa", "authentication"},
			},
			{
				ID:          "9.1",
				Title:       "Physical Access",
				Description: "Restrict physical access to cardholder data",
				Category:    "Physical Security",
				Keywords:    []string{"physical access", "physical security", "datacenter", "facility"},
			},
			{
				ID:          "10.1",
				Title:       "Audit Logging",
				Description: "Log and monitor all access to system components",
				Category:    "Logging",
				Keywords:    []string{"audit log", "logging", "access log", "event log"},
			},
			{
				ID:          "11.1",
				Title:       "Security Testing",
				Description: "Test security systems and processes regularly",
				Category:    "Testing",
				Keywords:    []string{"security testing", "vulnerability scan", "penetration test", "security assessment"},
			},
			{
				ID:          "12.1",
				Title:       "Security Policy",
				Description: "Maintain a policy that addresses information security",
				Category:    "Policy",
				Keywords:    []string{"security policy", "information security policy", "governance"},
			},
			{
				ID:          "12.6",
				Title:       "Security Awareness",
				Description: "Implement a security awareness program",
				Category:    "Awareness",
				Keywords:    []string{"security awareness", "training", "education", "awareness program"},
			},
			{
				ID:          "12.10",
				Title:       "Incident Response",
				Description: "Implement an incident response plan",
				Category:    "Incident Response",
				Keywords:    []string{"incident response", "incident", "security incident", "breach response"},
			},
		},
	}
}
